import { Control } from "./Control";
import type { IControlParams } from "./Control";
import type { IMouseState } from "../renderer/RendererEvents";
import { Quat } from "../math/Quat";
import { Sphere } from "../bv/Sphere";
import { Vec2 } from "../math/Vec2";
import { Vec3 } from "../math/Vec3";
interface IEarthNavigationParams extends IControlParams {
    speed?: number;
    fixedUp?: boolean;
}
export declare class MouseNavigation extends Control {
    speed: number;
    force: Vec3;
    force_h: number;
    force_v: number;
    vel: Vec3;
    vel_h: number;
    vel_v: number;
    mass: number;
    vel_roll: number;
    force_roll: number;
    protected _lookPos: Vec3 | undefined;
    protected _grabbedPoint: Vec3 | null;
    protected _targetZoomPoint: Vec3 | null;
    protected _targetDragPoint: Vec3 | null;
    protected _targetRotationPoint: Vec3 | null;
    protected _grabbedSphere: Sphere;
    protected _wheelDirection: number;
    protected _currScreenPos: Vec2;
    protected _tUp: Vec3;
    protected _tRad: number;
    protected _shiftBusy: boolean;
    protected fixedUp: boolean;
    protected _curPitch: number;
    protected _curYaw: number;
    protected _curRoll: number;
    protected _rot: Quat;
    protected _eye0: Vec3;
    protected _grabbedCameraHeight: number;
    protected _newEye: Vec3;
    protected _isTouchPad: boolean;
    protected _velInertia: number;
    protected _hold: boolean;
    protected _prevVel: Vec3;
    protected _screenPosIsChanged: boolean;
    protected _rotHDir: number;
    protected _rotVDir: number;
    constructor(options?: IEarthNavigationParams);
    oninit(): void;
    onactivate(): void;
    ondeactivate(): void;
    protected onDraw(): void;
    _onShiftFree: () => void;
    protected _onMouseMove: (e: IMouseState) => void;
    protected _onMouseEnter: (e: IMouseState) => void;
    protected _onMouseLeave: () => void;
    protected _onRHold: (e: IMouseState) => void;
    protected _handleRotation(): void;
    protected _onRDown: (e: IMouseState) => void;
    protected _getTargetPoint(p: Vec2): Vec3 | null;
    protected _onMouseWheel: (e: IMouseState) => void;
    protected _onLDown: (e: IMouseState) => void;
    protected _onLHold: (e: IMouseState) => void;
    protected _onLUp: (e: IMouseState) => void;
    protected _handleDrag(): void;
    protected _corrRoll(): void;
    protected _handleZoom(): void;
    protected _updateVel(): void;
    protected _updateVel_h(): void;
    protected _updateVel_v(): void;
    protected _updateVel_roll(): void;
    protected get dt(): number;
    stop(): void;
}
export {};
