import { Dialog, type IDialogParams } from "../../ui/Dialog";
import { GeoObjectEditorScene } from "./GeoObjectEditorScene";
import { Entity } from "../../entity/Entity";
import { Input } from "../../ui/Input";
import { Checkbox } from "../../ui/Checkbox";
import { Button } from "../../ui/Button";
import { Vec3 } from "../../math/Vec3";
interface IGeoObjectPropertiesDialog extends IDialogParams {
    model: GeoObjectEditorScene;
}
export declare class GeoObjectPropertiesDialog extends Dialog<GeoObjectEditorScene> {
    protected _relativePositionView: Checkbox;
    protected _lonView: Input;
    protected _latView: Input;
    protected _heightView: Input;
    protected _xView: Input;
    protected _yView: Input;
    protected _zView: Input;
    protected _absXView: Input;
    protected _absYView: Input;
    protected _absZView: Input;
    protected _pitchView: Input;
    protected _yawView: Input;
    protected _rollView: Input;
    protected _absolutePitchView: Input;
    protected _absoluteYawView: Input;
    protected _absoluteRollView: Input;
    protected _scaleView: Input;
    protected _scaleXView: Input;
    protected _scaleYView: Input;
    protected _scaleZView: Input;
    protected _groundBtn: Button;
    constructor(params: IGeoObjectPropertiesDialog);
    render(params: any): this;
    protected _onVisibility: (vis: boolean) => void;
    remove(): void;
    protected _initSceneEvents(): void;
    protected _clearSceneEvents(): void;
    protected _onSelect: (entity: Entity) => void;
    protected _refresh(entity: Entity): void;
    hide(): void;
    protected _onUnselect: (entity: Entity) => void;
    protected _onChangeRelativePosition: (checked: boolean) => void;
    protected _onPosition: (pos: Vec3, entity: Entity) => void;
    protected _onPitch: (a: number, entity: Entity) => void;
    protected _onYaw: (a: number, entity: Entity) => void;
    protected _onRoll: (a: number, entity: Entity) => void;
    protected _onChangeLon: (val: string) => void;
    protected _onChangeLat: (val: string) => void;
    protected _onChangeHeight: (val: string) => void;
    protected _onChangeX: (val: string) => void;
    protected _onChangeY: (val: string) => void;
    protected _onChangeZ: (val: string) => void;
    protected _onChangeAbsoluteX: (val: string) => void;
    protected _onChangeAbsoluteY: (val: string) => void;
    protected _onChangeAbsoluteZ: (val: string) => void;
    protected _onChangePitch: (val: string) => void;
    protected _onChangeYaw: (val: string) => void;
    protected _onChangeRoll: (val: string) => void;
    protected _onChangeAbsolutePitch: (val: string) => void;
    protected _onChangeAbsoluteYaw: (val: string) => void;
    protected _onChangeAbsoluteRoll: (val: string) => void;
    protected _onChangeScale: (val: string) => void;
    protected _onChangeScaleX: (val: string) => void;
    protected _onChangeScaleY: (val: string) => void;
    protected _onChangeScaleZ: (val: string) => void;
    protected _onGround: () => void;
}
export {};
